import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { localFont } from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const helveticaNeue = localFont({
  // https://typography.fandom.com/wiki/Helvetica_Neue
  // https://www.cdnfonts.com/helvetica-neue-5.font
  src: [
      {
      path: '../public/fonts/HelveticaNeueRoman.otf', // Adjust filename
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/HelveticaNeueMedium.otf', // Adjust filename
      weight: '600',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-helvetica-neue',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
