import "boxicons/css/boxicons.min.css";
import Header from "@/components/layout/header";
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "../styles/globals.css";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${lexend.variable} h-full antialiased`}>
      <Header />
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
